# Generated by Django 5.2.15 on 2026-06-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10, verbose_name='Статус платежу')),
                ('type', models.CharField(choices=[('BOOKING', 'Booking'), ('CANCELLATION', 'Cancellation Fee'), ('OVERSTAY', 'Overstay Fee'), ('NO_SHOW', 'No Show Fee')], max_length=15, verbose_name='Тип платежу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума до оплати')),
                ('session_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='Посилання на оплату Stripe')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Бронювання')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
