# Generated by Django 5.2.15 on 2026-06-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0003_alter_booking_price_per_night"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Payment status",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOOKING", "Booking"),
                            ("CANCELLATION", "Cancellation Fee"),
                            ("OVERSTAY", "Overstay Fee"),
                            ("NO_SHOW", "No Show Fee"),
                        ],
                        max_length=15,
                        verbose_name="Payment type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Amount to be paid",
                    ),
                ),
                (
                    "session_url",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Stripe payment link",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Session ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                        verbose_name="bookings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
