# Generated by Django 5.2.15 on 2026-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Stripe link",
            ),
        ),
    ]
