# Generated by Django 5.2.15 on 2026-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("BOOKING", "Booking"),
                    ("CANCELLATION_FEE", "Cancellation Fee"),
                    ("OVERSTAY_FEE", "Overstay Fee"),
                    ("NO_SHOW_FEE", "No Show Fee"),
                ],
                max_length=20,
                verbose_name="Payment type",
            ),
        ),
    ]
