# Generated by Django 5.2.15 on 2026-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_late_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
